-- PG 18 + TypeORM: updatedAt columns need DB defaults when ORM sends DEFAULT
ALTER TABLE "User" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "UserSettings" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ThreatTemplate" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Routine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "LandingPage" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
